### ISSUE TITLE
User profile data is returned on JWT authentication.

### ISSUE THREAD

**Issue by haccks** [jazzband/dj-rest-auth#174] opened 2020-11-22 21:36 UTC
When login using JWT authentication along with tokens I get user profile data. What I expected is only tokens.   

Response:

```
HTTP 200 OK
Allow: POST, OPTIONS
Content-Type: application/json
Vary: Accept


{
    "access_token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ0b2tlbl90eXBlIjoiYzkjZXNzIiwiZXhwIjoxNjA2MDgwpDMxLCJqdGkiOiI3MzdjNDM0NjMyODc0NmI2YTI3NmJlMTE2ZmQ2ODA3OCIsInVzZXJfaWQiOjN9.3WrsswwySVEgU8NWQzWu4KTF4g3qWRYvIM0ZActX5wc",
    "refresh_token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ0b2tlbl90eXBlIjoicmVMdMVzaCIsImV4cCI6MTYwNjE2NjkzMSwianRpIjoiZTQ0ZjJkZTdjM2U3NDUxMWE2OWM2YWYxOWRiNWJlZTEiLCJ1c2VyX2lkIjozfQ.U2hVDtaHXkJTKFCPRXI5G-d2u4aJA0a7yBocpCvVkPk",
    "user": {
        "email": "xxxxxxxxxx",
        "profile": {
            "name": "foo",
            "dob": null,
            "gender": "M",
        }
    }
}
```

**Comment by iMerica** [comment] 2020-11-23 05:37
Hi ,

This user field has existed since the beginning of this project and was not added in error. Given that a JWT can include such data in the claims payload, I see this at best convenient and at worst redundant.

If you would like to omit it, you can override the login view or login serializer. I'm going to close this since it's not a bug.

**Closed by iMerica** 2020-11-23 05:37 UTC
