### ISSUE TITLE
Deactivate User endpoints

### ISSUE THREAD

**Issue by GitRon** [jazzband/dj-rest-auth#145] opened 2020-09-16 07:57 UTC
Hi there,

I am just trying out your package. Looks good so far but I struggle deactivating the user routes:

![grafik](https://user-images.githubusercontent.com/3176075/93308749-f1e28a00-f802-11ea-83fe-ea4bf42ce705.png)

I need a custom ViewSet and don't want to have some "uncontrolled" second endpoints lying around.

Any ideas if this is possible? If not, a config var would be awesome.

Thanks and best regards   
Ronny

**Comment by iMerica** [comment] 2020-09-17 00:58
You can override it with your own views and just return HTTP 400 on every HTTP Method.

**Comment by iMerica** [comment] 2020-09-19 18:44
Hi Ronny, I hope that was able to work for you. I'm going to close this out for now since everything is working as intended.

**Closed by iMerica** 2020-09-19 18:44 UTC

**Comment by GitRon** [comment] 2020-09-21 12:13
Sorry for the late reply. djangoCon is my excuse 😎 I think it would be really nice to add a settings variable to disable this. Small change but big win if you need it. What do you think? Default would obviously stay like it is now.
