### ISSUE TITLE
Support for Django 3.1

### ISSUE THREAD

**Issue by bufke** [jazzband/dj-rest-auth#167] opened 2020-11-12 01:38 UTC
Hello, was it intentional to remove support for Django 3.1 in the 2.0.0 release? I've been using dj-rest-auth for some time with Django 3.1 without incident and I couldn't find any open issues as to what might be wrong with 3.1 support.

Note that some package managers such Poetry do [not allow overriding sub dependency requirements](https://github.com/python-poetry/poetry/issues/697).

**Comment by iMerica** [comment] 2020-11-12 04:40
Hi @bufke,

Thanks for raising this issue. As it turns out, Django 3.1 was not the root cause of recent test failures – it was an issue with Django-All auth. I've pushed 2.0.1 to PyPi to correct this.

For context – I run tests on this package across all possible combinations of major Python 3 versions and Django 2 and Django 3 versions. We suddenly had failing tests that pointed towards a combination of Django 3.1 + latest Django All-Auth. However after more investigation it appears that the issue was only with All Auth.

**Comment by iMerica** [comment] 2020-11-23 05:45
I'm going to close this since 3.1 is supported again. Apologies for any inconveniences.

**Closed by iMerica** 2020-11-23 05:45 UTC
